[package]
name = "mandelbrot-ints"
version = "0.1.0"
authors = ["Joe Martinson <joe.martinson@modalai.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-complex = "0.4.0"
image = "0.23.14"
rayon = "1.5.0"